#!/usr/bin/env python3
"""Emit untrusted bitmap/ordered-block inputs; Lean reader equalities are mandatory.

Authorship note: this was researched and written by an AI coding agent
(OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
posted from this account.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import inode_certificates as inode
import images


def inode_blocks(record, entries):
    nb = (record[4] + 1023) // 1024
    return (([record[-1]] if nb > 12 else []) + list(record[5:5 + min(nb, 12)]) +
            entries[:max(nb - 12, 0)])


def self_test():
    inode.self_test()
    record = (2, 0, 0, 1, 13 * 1024) + tuple(range(47, 60))
    inode.require(inode_blocks(record, [60] + [0] * 255) == [59] + list(range(47, 59)) + [60],
                  'indirect-first order regression')
    repeated = (2, 0, 0, 1, 2 * 1024) + (47, 47) + (0,) * 11
    inode.require(inode_blocks(repeated, [0] * 256) == [47, 47], 'duplicates were erased')
    print('Bitmap producer preserves indirect-first order and repeated blocks.')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('source', type=Path)
    p.add_argument('--check', action='store_true')
    p.add_argument('--self-test', action='store_true')
    args = p.parse_args()
    if args.self_test:
        self_test()
    lock = json.loads((inode.ROOT / 'upstream.lock.json').read_text())
    inode.require(lock['repositories']['xv6iris']['revision'] == inode.PIN, 'paper pin changed')
    revision = subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip()
    source = (args.source / inode.RAW).read_bytes()
    original = subprocess.check_output(['git', '-C', str(args.source), 'show', inode.PIN + ':' + inode.RAW])
    inode.validate_source(revision, source, original)
    raw = images.extract(source.decode(), 'fsimg_hex')
    inode.require(len(raw) == 2048000 and hashlib.sha256(raw).hexdigest() == inode.DIGEST,
                  'raw image hash/size differs')
    import struct
    sb = struct.unpack_from('<8I', raw, 1024)
    inode.require(sb == inode.EXPECTED_SB, 'superblock changed')
    used = []
    for i in range(sb[3]):
        record = inode.read_inode(raw, i, sb[6])
        if record[0] != 0:
            used.extend(inode_blocks(record, inode.indirect(raw, record)))
    bitmap = raw[sb[7] * 1024:(sb[7] + 1) * 1024]
    body = 'import Xv6.Fs.BitmapDefs\n\n'
    body += inode.provenance_header(hashlib.sha256(source).hexdigest()).replace(
        'Generated by tools/inode_certificates.py', 'Generated by tools/bitmap_certificates.py')
    body += '\nnamespace Xv6.Generated.Bitmap\n\n'
    body += 'def orderedBlocks : List Int := [' + ', '.join(map(str, used)) + ']\n\n'
    body += 'def bitmapBytes : List (BitVec 8) := [' + ', '.join(map(str, bitmap)) + ']\n\n'
    body += 'end Xv6.Generated.Bitmap\n'
    inode.emit(inode.ROOT / 'Xv6/Generated/BitmapInputs.lean', body, args.check)
    print(f'Reproduced {len(used)} ordered blocks and {len(bitmap)} bitmap bytes; Lean equalities remain mandatory.')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error
