#!/usr/bin/env python3
"""Emit untrusted root directory bytes; the Lean reader equality is mandatory.

Authorship note: this was researched and written by an AI coding agent
(OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
posted from this account.
"""
import argparse
import hashlib
import json
import struct
import subprocess
from pathlib import Path
import inode_certificates as inode
import images


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('source', type=Path)
    p.add_argument('--check', action='store_true')
    p.add_argument('--self-test', action='store_true')
    args = p.parse_args()
    if args.self_test:
        inode.self_test()
    lock = json.loads((inode.ROOT / 'upstream.lock.json').read_text())
    inode.require(lock['repositories']['xv6iris']['revision'] == inode.PIN, 'paper pin changed')
    revision = subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip()
    source = (args.source / inode.RAW).read_bytes()
    original = subprocess.check_output(['git', '-C', str(args.source), 'show', inode.PIN + ':' + inode.RAW])
    inode.validate_source(revision, source, original)
    raw = images.extract(source.decode(), 'fsimg_hex')
    inode.require(len(raw) == 2048000 and hashlib.sha256(raw).hexdigest() == inode.DIGEST,
                  'raw image hash/size differs')
    sb = struct.unpack_from('<8I', raw, 1024)
    inode.require(sb == inode.EXPECTED_SB, 'superblock changed')
    record = inode.read_inode(raw, 1, sb[6])
    inode.require(record[0] == 1 and record[4] == 1024 and record[5] == 47 and not any(record[6:]),
                  'root is not the certified single-block record')
    directory = raw[47 * 1024:48 * 1024]
    body = 'import Xv6.Fs.DirentDefs\n\n'
    body += inode.provenance_header(hashlib.sha256(source).hexdigest()).replace(
        'Generated by tools/inode_certificates.py', 'Generated by tools/directory_certificates.py')
    body += '\nnamespace Xv6.Generated.Directory\n\n'
    body += 'def rootBytes : List (BitVec 8) := [' + ', '.join(map(str, directory)) + ']\n\n'
    body += 'end Xv6.Generated.Directory\n'
    inode.emit(inode.ROOT / 'Xv6/Generated/DirectoryInputs.lean', body, args.check)
    print('Reproduced 1024 root-directory bytes; the actual block-reader equality remains mandatory.')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error
