#!/usr/bin/env python3
"""Recover exact paper image bytes and emit reproducible Lean hex and packed constants.

This is an untrusted data importer. Image decoding and ELF/filesystem validation
remain proof obligations; matching hashes is provenance evidence, not a proof.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
IMAGES = {
    "KernelElf": ("kernel-rocq/KernelElfRaw.v", "kernel_elf_hex", 285560,
                  "b4bd19f162efb9584b841508408035de7e41a4c680311a514e4e78b8f06eedd8"),
    "FsImg": ("kernel-rocq/FsImgRaw.v", "fsimg_hex", 2048000,
              "77f42e2f20c0c2c72234dc9ea034f808a26a003f50e7bba62befe8c174bd07b5"),
}


def extract(text, prefix):
    pattern = rf'Definition {prefix}_chunk(\d+) : PrimString.string := "([0-9a-f]*)"%pstring\.'
    matches = re.findall(pattern, text)
    declared = re.findall(rf'Definition {prefix}_chunk(\d+)\b', text)
    if len(declared) != len(matches):
        raise ValueError("malformed raw chunk declaration")
    if not matches:
        raise ValueError(f"no raw chunks for {prefix}")
    if [int(i) for i, _ in matches] != list(range(len(matches))):
        raise ValueError("raw chunks are missing, duplicated or out of order")
    if any(len(h) % 2 for _, h in matches):
        raise ValueError("odd-length byte chunk")
    return bytes.fromhex("".join(h for _, h in matches))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    lock = json.loads((ROOT / "upstream.lock.json").read_text())
    revision = lock["repositories"]["xv6iris"]["revision"]
    actual = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=args.source, text=True).strip()
    if actual != revision:
        raise SystemExit(f"source revision mismatch: {actual}")
    for name, (relative, prefix, size, digest) in IMAGES.items():
        raw = extract((args.source / relative).read_text(), prefix)
        if len(raw) != size or hashlib.sha256(raw).hexdigest() != digest:
            raise SystemExit(f"{name}: paper image hash/size mismatch")
        hexdata = raw.hex()
        chunks = [hexdata[i:i+8192] for i in range(0, len(hexdata), 8192)]
        body = "\n".join(f'  "{chunk}"' + ("," if i < len(chunks)-1 else "")
                         for i, chunk in enumerate(chunks))
        rendered = (f"-- Generated by tools/images.py. DO NOT EDIT.\n"
                    f"-- xv6 software: see LICENSES/xv6-riscv.txt for copyright and permission.\n"
                    f"-- Source: mit-pdos/xv6iris@{revision}/{relative}\n"
                    f"-- Byte length: {size}; SHA256: {digest}\n"
                    f"namespace Xv6.Generated\n\n"
                    f"def {name[0].lower()+name[1:]}HexChunks : List String := [\n{body}\n]\n\n"
                    f"end Xv6.Generated\n")
        pages = [int.from_bytes(raw[i:i+4096], "little") for i in range(0, len(raw), 4096)]
        packed_body = ",\n".join("  " + hex(page) for page in pages)
        packed = (f"-- Generated by tools/images.py. DO NOT EDIT.\n"
                  f"-- xv6 software: see LICENSES/xv6-riscv.txt for copyright and permission.\n"
                  f"-- Source: mit-pdos/xv6iris@{revision}/{relative}\n"
                  f"-- Byte length: {size}; SHA256: {digest}\n"
                  "import Xv6.Image.Packed\n\nnamespace Xv6.Generated\n\n"
                  f"def {name[0].lower()+name[1:]}Packed : Xv6.Image.Packed := {{\n"
                  f"  byteLength := {size}\n  pages := [\n{packed_body}\n  ]\n}}\n\n"
                  "end Xv6.Generated\n")
        for suffix, content in [("", rendered), ("Packed", packed)]:
            output = ROOT / "Xv6/Generated" / (name + suffix + ".lean")
            if args.check:
                if output.read_text() != content:
                    raise SystemExit(f"stale generated image: {output}")
            else:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text(content)
        print(f"{name}: {size} bytes sha256 {digest}")


if __name__ == "__main__":
    main()
