#!/usr/bin/env python3
"""Recover exact paper image bytes and emit reproducible Lean hex and packed constants.

This is an untrusted data importer. Generated Lean certificates prove strict
hex/packed encoding equality only after kernel checking; ELF and filesystem
validation remain separate. Matching hashes is provenance evidence, not a proof.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
IMAGES = {
    "KernelElf": ("kernel-rocq/KernelElfRaw.v", "kernel_elf_hex", 285560,
                  "b4bd19f162efb9584b841508408035de7e41a4c680311a514e4e78b8f06eedd8"),
    "FsImg": ("kernel-rocq/FsImgRaw.v", "fsimg_hex", 2048000,
              "77f42e2f20c0c2c72234dc9ea034f808a26a003f50e7bba62befe8c174bd07b5"),
}


def extract(text, prefix):
    pattern = rf'Definition {prefix}_chunk(\d+) : PrimString.string := "([0-9a-f]*)"%pstring\.'
    matches = re.findall(pattern, text)
    declared = re.findall(rf'Definition {prefix}_chunk(\d+)\b', text)
    if len(declared) != len(matches):
        raise ValueError("malformed raw chunk declaration")
    if not matches:
        raise ValueError(f"no raw chunks for {prefix}")
    if [int(i) for i, _ in matches] != list(range(len(matches))):
        raise ValueError("raw chunks are missing, duplicated or out of order")
    if any(len(h) % 2 for _, h in matches):
        raise ValueError("odd-length byte chunk")
    return bytes.fromhex("".join(h for _, h in matches))


PAGE_BYTES = 4096
CERTIFICATE_SHARD_PAGES = 8
GENERATED_HEADER = "-- Generated by tools/images.py. DO NOT EDIT.\n"


def balanced(items, leaf, combine):
    """Keep both the data expression and its proof at logarithmic depth."""
    if not items:
        raise ValueError("empty balanced block")
    if len(items) == 1:
        return leaf(items[0])
    middle = len(items) // 2
    return combine(balanced(items[:middle], leaf, combine),
                   balanced(items[middle:], leaf, combine))


def provenance(revision, relative, size, digest):
    return (GENERATED_HEADER +
            "-- xv6 software: see LICENSES/xv6-riscv.txt for copyright and permission.\n" +
            f"-- Source: mit-pdos/xv6iris@{revision}/{relative}\n" +
            f"-- Byte length: {size}; SHA256: {digest}\n")


def render_images(inputs, revision):
    """Emit exact bytes and ordinary Lean proof terms; this generator is untrusted.

    Each raw page is a balanced append of two-character literal strings. Its
    certificate has the identical append tree over 256 shared, checked byte
    certificates. Thus neither elaboration nor kernel checking has to evaluate
    a giant literal string concatenation or decode 4096 bytes recursively.
    """
    outputs = {}
    pages = []
    page_ids = {}
    image_pages = {}
    for name, raw in inputs.items():
        indexes = []
        for offset in range(0, len(raw), PAGE_BYTES):
            page = raw[offset:offset + PAGE_BYTES]
            if page not in page_ids:
                page_ids[page] = len(pages)
                pages.append(page)
            indexes.append(page_ids[page])
        image_pages[name] = indexes

    leaves = [GENERATED_HEADER,
              "-- Shared one-byte decoding certificates, checked by kernel reflexivity.\n",
              "import Xv6.Image.EncodingProofs\n\n",
              "namespace Xv6.Generated.Encoding\nopen Xv6.Image\n\n"]
    for byte in range(256):
        leaves.append(f'theorem byte{byte:02x} : HexBlockString "{byte:02x}" 1 {byte} := by\n'
                      "  apply HexBlock.of_check\n  rfl\n\n")
    leaves.append("end Xv6.Generated.Encoding\n")
    outputs["EncodingCertificateLeaves.lean"] = "".join(leaves)

    for start in range(0, len(pages), CERTIFICATE_SHARD_PAGES):
        shard = start // CERTIFICATE_SHARD_PAGES
        data_name = f"EncodingCertificateData{shard:03d}"
        proof_name = f"EncodingCertificatePages{shard:03d}"
        data = [GENERATED_HEADER,
                "-- Exact image bytes as balanced literal hexadecimal blocks.\n",
                "-- xv6 software: see LICENSES/xv6-riscv.txt for copyright and permission.\n",
                f"-- Page data extracted from mit-pdos/xv6iris@{revision}.\n",
                "namespace Xv6.Generated.Encoding\n\n"]
        proofs = [GENERATED_HEADER,
                  "-- Balanced composition of shared kernel-checked byte certificates.\n",
                  "import Xv6.Generated.EncodingCertificateLeaves\n",
                  f"import Xv6.Generated.{data_name}\n\n",
                  "set_option maxRecDepth 20000\n",
                  "set_option maxHeartbeats 8000000\n",
                  "set_option exponentiation.threshold 65536\n\n",
                  "namespace Xv6.Generated.Encoding\nopen Xv6.Image\n\n"]
        for index in range(start, min(start + CERTIFICATE_SHARD_PAGES, len(pages))):
            page = pages[index]
            text_expr = balanced(page, lambda byte: f'"{byte:02x}"',
                                 lambda left, right: f"({left} ++ {right})")
            proof_expr = balanced(page, lambda byte: f"byte{byte:02x}",
                                  lambda left, right: f"(hexBlockString_append {left} {right})")
            data.append(f"def page{index:03d} : String :=\n  {text_expr}\n\n")
            proofs.append(f"theorem page{index:03d}_encoding : HexBlockString page{index:03d} "
                          f"{len(page)} {hex(int.from_bytes(page, 'little'))} :=\n  {proof_expr}\n\n")
        data.append("end Xv6.Generated.Encoding\n")
        proofs.append("end Xv6.Generated.Encoding\n")
        outputs[data_name + ".lean"] = "".join(data)
        outputs[proof_name + ".lean"] = "".join(proofs)

    for name, raw in inputs.items():
        relative, _, size, digest = IMAGES[name]
        lower = name[0].lower() + name[1:]
        indexes = image_pages[name]
        shards = sorted({index // CERTIFICATE_SHARD_PAGES for index in indexes})
        header = provenance(revision, relative, size, digest)
        imports = "".join(f"import Xv6.Generated.EncodingCertificateData{shard:03d}\n"
                          for shard in shards)
        raw_body = ",\n".join(f"  Encoding.page{index:03d}" for index in indexes)
        outputs[name + ".lean"] = (header + imports + "\nnamespace Xv6.Generated\n\n" +
            f"def {lower}HexChunks : List String := [\n{raw_body}\n]\n\nend Xv6.Generated\n")
        packed_pages = [int.from_bytes(raw[i:i + PAGE_BYTES], "little")
                        for i in range(0, len(raw), PAGE_BYTES)]
        packed_body = ",\n".join("  " + hex(page) for page in packed_pages)
        outputs[name + "Packed.lean"] = (header + "import Xv6.Image.Packed\n\n" +
            "namespace Xv6.Generated\n\n" +
            f"def {lower}Packed : Xv6.Image.Packed := {{\n" +
            f"  byteLength := {size}\n  pages := [\n{packed_body}\n  ]\n}}\n\n" +
            "end Xv6.Generated\n")
        cert_imports = "".join(f"import Xv6.Generated.EncodingCertificatePages{shard:03d}\n"
                               for shard in shards)
        term = f"(.last Encoding.page{indexes[-1]:03d}_encoding (by decide))"
        for index in reversed(indexes[:-1]):
            term = f"(.full Encoding.page{index:03d}_encoding {term})"
        outputs["EncodingCertificate" + name + ".lean"] = (header +
            f"import Xv6.Generated.{name}\nimport Xv6.Generated.{name}Packed\n" + cert_imports +
            "\nset_option maxRecDepth 20000\nset_option maxHeartbeats 8000000\n\n" +
            "namespace Xv6.Generated\nopen Xv6.Image\n\n" +
            f"theorem {lower}Encoding : HexPages {lower}HexChunks {lower}Packed.pages " +
            f"{lower}Packed.byteLength :=\n  {term}\n\n" +
            f"theorem {lower}_decode_eq : decodeChunks {lower}HexChunks =\n" +
            f"    some (ByteArray.mk {lower}Packed.toBytes.toArray) :=\n" +
            f"  {lower}Packed.decode_eq_of_hexPages {lower}Encoding\n\n" +
            f"theorem {lower}_lookup_eq (decoded : decodeChunks {lower}HexChunks = some raw) (offset : Nat) :\n" +
            f"    {lower}Packed.getByte? offset = raw.data.toList[offset]? :=\n" +
            f"  {lower}Packed.lookup_eq_of_hexPages {lower}Encoding decoded offset\n\n" +
            "end Xv6.Generated\n")
    return outputs, len(pages)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    lock = json.loads((ROOT / "upstream.lock.json").read_text())
    revision = lock["repositories"]["xv6iris"]["revision"]
    actual = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=args.source, text=True).strip()
    if actual != revision:
        raise SystemExit(f"source revision mismatch: {actual}")
    inputs = {}
    for name, (relative, prefix, size, digest) in IMAGES.items():
        raw = extract((args.source / relative).read_text(), prefix)
        if len(raw) != size or hashlib.sha256(raw).hexdigest() != digest:
            raise SystemExit(f"{name}: paper image hash/size mismatch")
        inputs[name] = raw
    outputs, count = render_images(inputs, revision)
    directory = ROOT / "Xv6/Generated"
    existing = {p.name for p in directory.glob("EncodingCertificate*.lean")}
    stale = existing - set(outputs)
    for filename in sorted(stale):
        output = directory / filename
        if args.check or not output.read_text().startswith(GENERATED_HEADER):
            raise SystemExit(f"unexpected generated certificate file: {output}")
        output.unlink()
    for filename, content in outputs.items():
        output = directory / filename
        if args.check:
            if not output.exists() or output.read_text() != content:
                raise SystemExit(f"stale generated image/certificate: {output}")
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(content)
    for name, (_, _, size, digest) in IMAGES.items():
        print(f"{name}: {size} bytes sha256 {digest}")
    print(f"Encoding certificates: {count} unique pages; 256 byte leaves; {len(outputs)} generated files")


if __name__ == "__main__":
    main()
