#!/usr/bin/env python3
"""Generate untrusted W3 literal inputs, each checked against actual Lean readers.

Authorship note: this was researched and written by an AI coding agent
(OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
posted from this account.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PIN = 'fa7f0a01c4b40489fac8ad303f079c2dfc7a1476'
RAW = 'kernel-rocq/FsImgRaw.v'
DIGEST = '77f42e2f20c0c2c72234dc9ea034f808a26a003f50e7bba62befe8c174bd07b5'
EXPECTED_SB = (0x10203040, 2000, 1953, 200, 31, 2, 33, 46)


def require(test, message):
    if not test:
        raise ValueError(message)


def validate_source(revision, source, original):
    require(revision == PIN, 'source checkout revision differs')
    require(source == original, 'raw source differs from pinned Git blob')


def read_inode(raw, index, start):
    # Actual DinodeEnc geometry: index wraps to uint32 before division/slot.
    index %= 2**32
    offset = ((index // 16) + start) * 1024 + (index % 16) * 64
    require(0 <= offset and offset + 64 <= len(raw), 'concrete inode outside raw image')
    return struct.unpack_from('<HHHHI13I', raw, offset)


def indirect(raw, record):
    ib = record[-1]
    if ib == 0:
        return [0] * 256
    require(ib * 1024 + 1024 <= len(raw), 'concrete indirect block outside raw image')
    return list(struct.unpack_from('<256I', raw, ib * 1024))


def check_w3(record, entries, sb):
    ty, _, _, nlink, size, *addrs = record
    nb = (size + 1023) // 1024
    good = lambda address: sb[7] + 1 <= address < sb[1]
    return (ty in (1, 2, 3) and nlink >= 1 and size <= 268 * 1024 and
            all(good(addrs[k]) if k < nb else addrs[k] == 0 for k in range(12)) and
            (addrs[12] == 0 if nb <= 12 else good(addrs[12])) and
            all(good(entries[j]) if j < nb - 12 else entries[j] == 0 for j in range(256)))


def provenance_header(digest):
    return ('/-! Generated by tools/inode_certificates.py; do not edit.\n'
            f'Pinned FsImgRaw.v at {PIN}, SHA256 {digest}.\n'
            'Literal inputs are untrusted until the accompanying Lean reader equalities check.\n'
            'Kernel software: Copyright (c) 2006-2024 Frans Kaashoek, Robert Morris, Russ Cox,\n'
            'Massachusetts Institute of Technology; see LICENSES/xv6-riscv.txt.\n'
            'Authorship note: this was researched and written by an AI coding agent\n'
            '(OpenAI Codex), working on Jason Gross\'s behalf; Jason reviews what is\n'
            'posted from this account.\n-/\n')


def emit(path, text, check):
    if check:
        require(path.exists() and path.read_text() == text, 'generated file differs: ' + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def self_test():
    sb = EXPECTED_SB
    record = (2, 0, 0, 1, 0) + (0,) * 13
    require(check_w3(record, [0] * 256, sb), 'empty file regression')
    mutations = []
    for index, value in [(0, 0), (3, 0), (4, 268 * 1024 + 1), (5, 47), (17, 47)]:
        changed = list(record); changed[index] = value; mutations.append(tuple(changed))
    require(all(not check_w3(r, [0] * 256, sb) for r in mutations), 'W3 rejected-field regression')
    require(not check_w3(record, [47] + [0] * 255, sb), 'unused indirect entry regression')
    try: read_inode(b'', 0, 0)
    except ValueError: pass
    else: raise ValueError('truncated image accepted')
    for revision, source, original in [('0' * 40, b'x', b'x'), (PIN, b'x', b'y')]:
        try: validate_source(revision, source, original)
        except ValueError: pass
        else: raise ValueError('wrong source revision/blob accepted')
    with tempfile.TemporaryDirectory(prefix='inode-w3-check-') as directory:
        path = Path(directory) / 'certificate.lean'
        path.write_text('altered output')
        try: emit(path, 'expected output', True)
        except ValueError: pass
        else: raise ValueError('modified generated output accepted')
    print('W3 negative tests passed: fields, truncation, source revision/blob, modified output.')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('source', type=Path)
    p.add_argument('--check', action='store_true')
    p.add_argument('--self-test', action='store_true')
    args = p.parse_args()
    if args.self_test: self_test()
    lock = json.loads((ROOT / 'upstream.lock.json').read_text())
    require(lock['repositories']['xv6iris']['revision'] == PIN, 'paper pin changed')
    revision = subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip()
    source = (args.source / RAW).read_bytes()
    original = subprocess.check_output(['git', '-C', str(args.source), 'show', PIN + ':' + RAW])
    validate_source(revision, source, original)
    sys.path.insert(0, str(ROOT / 'tools'))
    import images
    raw = images.extract(source.decode(), 'fsimg_hex')
    require(len(raw) == 2048000 and hashlib.sha256(raw).hexdigest() == DIGEST, 'raw image hash/size differs')
    sb = struct.unpack_from('<8I', raw, 1024)
    require(sb == EXPECTED_SB, 'concrete superblock changed')
    records = {i: read_inode(raw, i, sb[6]) for i in range(sb[3])}
    live = [i for i, record in records.items() if record[0] != 0]
    require(live == list(range(1, 23)), 'actual live inode set changed')
    entries = {i: indirect(raw, records[i]) for i in live}
    require(all(check_w3(records[i], entries[i], sb) for i in live), 'host W3 diagnostic failed')
    source_hash = hashlib.sha256(source).hexdigest()
    header = provenance_header(source_hash)
    body = 'import Xv6.Fs.InodeW3Proofs\n\n' + header + '\nnamespace Xv6.Generated.InodeW3\n\n'
    manifest = {'xv6iris_revision': PIN, 'source': RAW, 'source_sha256': source_hash,
                'source_git_blob': subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', PIN + ':' + RAW], text=True).strip(),
                'image_sha256': DIGEST, 'image_size': len(raw), 'live_inodes': live,
                'reader_equalities_required': ['dinode', 'indirectEntries'],
                'host_w3_check': 'diagnostic only; all Lean leaf proofs mandatory'}
    body += 'def provenanceJSON : String := ' + json.dumps(json.dumps(manifest, sort_keys=True)) + '\n\n'
    for i in live:
        record = records[i]
        scalars = ', '.join(f'{v}#{16 if j < 4 else 32}' for j, v in enumerate(record[:5]))
        addrs = ', '.join(f'{v}#32' for v in record[5:])
        body += f'def record{i:02} : Fs.Dinode := ⟨{scalars}, [{addrs}]⟩\n\n'
        values = entries[i]
        literal = 'List.replicate 256 0' if not any(values) else '[' + ', '.join(map(str, values)) + ']'
        body += f'def entries{i:02} : List Int := {literal}\n\n'
    body += 'end Xv6.Generated.InodeW3\n'
    emit(ROOT / 'Xv6/Generated/InodeW3Data.lean', body, args.check)
    for i in live:
        leaf = ('import Xv6.Generated.InodeW3Data\nimport Xv6.Fs.DiskReaders\nimport Xv6.Fs.Image\n\n' + header +
                '\nset_option maxRecDepth 8192\nset_option maxHeartbeats 4000000\n\nnamespace Xv6.Generated.InodeW3\nopen Xv6.Fs Xv6.Fs.Image\n\n')
        leaf += f'theorem record{i:02}_eq : dinode blockView superblock {i} = record{i:02} := by\n  change dinode (blocks disk) superblock {i} = record{i:02}\n  rw [dinode_blocks]\n  decide\n\n'
        leaf += f'theorem entries{i:02}_eq : indirectEntries blockView record{i:02} = entries{i:02} := by\n  change indirectEntries (blocks disk) record{i:02} = entries{i:02}\n  rw [indirectEntries_blocks]\n  decide\n\n'
        leaf += f'theorem record{i:02}_checked : inodeInputValid superblock record{i:02} entries{i:02} = true := by decide\n\n'
        leaf += f'theorem inode{i:02}_valid : inodeValid blockView superblock (dinode blockView superblock {i}) = true :=\n  inodeValid_of_certified_inputs blockView superblock {i} record{i:02} entries{i:02}\n    record{i:02}_eq entries{i:02}_eq record{i:02}_checked\n\nend Xv6.Generated.InodeW3\n'
        emit(ROOT / f'Xv6/Generated/InodeW3Leaf{i:02}.lean', leaf, args.check)
    print('Reproduced 22 inode records and 22 indirect-entry inputs; every Lean leaf remains mandatory.')


if __name__ == '__main__':
    try: main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error
