#!/usr/bin/env python3
"""Import the pinned Rocq maps, preserving ordered first-winner semantics.

Untrusted data importer; Lean certificates separately check ELF correspondence.
Authorship note: researched and written by OpenAI Codex on Jason Gross's behalf.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
PIN = 'fa7f0a01c4b40489fac8ad303f079c2dfc7a1476'
FILES = ['kernel-rocq/KernelInstrs.v', 'kernel-rocq/KernelData.v',
         'kernel-rocq/KernelSyms.v', 'tools/dump_elf.py', 'kernel-rocq/KernelElfRaw.v']
HEX = r'0x[0-9a-f]+'
PAIR = re.compile(r'\(\((' + HEX + r')\)%Z, Z_to_bv 8 \((' + HEX + r')\)%Z\)')
INSN = re.compile(r'\(\(([0-9]+)\)%Z, MkKInstr \((' + HEX + r')\)%Z ([0-9]+)%nat \((' + HEX + r')\)%Z\)')


def require(condition, message):
    if not condition:
        raise ValueError(message)


def comments_removed(text):
    # Reject unbalanced/nested comments rather than silently eating source code.
    out, pos = [], 0
    while pos < len(text):
        start = text.find('(*', pos)
        if start == -1:
            out.append(text[pos:]); break
        out.append(text[pos:start])
        end = text.find('*)', start + 2)
        require(end != -1 and '(*' not in text[start + 2:end], 'unsupported/unclosed comment')
        pos = end + 2
    result = ''.join(out)
    require('*)' not in result, 'unmatched comment terminator')
    return result


def ordered_entries(text, prefix, kind, pattern):
    clean = comments_removed(text)
    chunks = {}
    rx = re.compile(r'Definition (' + prefix + r'_chunk[0-9]+) : list \(' + re.escape(kind) + r'\) := \[(.*?)\]\.', re.S)
    for name, body in rx.findall(clean):
        require(name not in chunks, 'duplicate chunk ' + name)
        pieces = body.strip().split(';') if body.strip() else []
        entries = []
        for piece in pieces:
            m = pattern.fullmatch(piece.strip())
            require(m is not None, 'unparsed entry in ' + name + ': ' + piece[:100])
            entries.append(tuple(int(x, 0) if x.startswith('0x') else int(x) for x in m.groups()))
        chunks[name] = entries
    joins = re.findall(r'Definition ' + prefix + r' : gmap Z .*? :=\s*list_to_map \(List.concat \[(.*?)\]\)\.', clean, re.S)
    require(len(joins) == 1, 'missing/ambiguous ordered map join ' + prefix)
    order = [s.strip() for s in joins[0].split(';') if s.strip()]
    require(set(order) == set(chunks) and len(order) == len(chunks), 'join omits/repeats/unknown chunks')
    # Follow the actual join, not file order or numeric suffix sorting.
    return [entry for name in order for entry in chunks[name]], order


def runs(entries):
    result = []
    for address, byte in entries:
        require(0 <= byte < 256, 'byte outside bv8 range')
        if not result or address != result[-1][0] + len(result[-1][1]) or address % 4096 == 0:
            result.append((address, bytearray()))
        result[-1][1].append(byte)
    return result


def first_map(entries):
    result = {}
    for address, byte in entries:
        result.setdefault(address, byte)
    return result


def header(provenance):
    return ('/-! Generated by tools/kernel_maps.py from ordered Rocq source maps.\n'
            'Do not edit. Regenerate with `python3 tools/kernel_maps.py .upstream/xv6iris`.\n'
            'xv6iris revision: ' + PIN + '\n' + provenance + '\n'
            'Kernel software: Copyright (c) 2006-2024 Frans Kaashoek, Robert Morris, Russ Cox,\n'
            'Massachusetts Institute of Technology. See LICENSES/xv6-riscv.txt.\n'
            'Authorship note: this importer/output was researched and written by an AI coding agent\n'
            '(OpenAI Codex), working on Jason Gross\'s behalf; Jason reviews what is posted from this account.\n-/\n')


def emit(path, text, check):
    if check:
        require(path.exists() and path.read_text() == text, 'generated file differs: ' + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def self_test():
    chunk = 'Definition m_chunk{} : list (Z * bv 8) := [((0x10)%Z, Z_to_bv 8 (0x{:x})%Z)].\n'
    join = 'Definition m : gmap Z (bv 8) := list_to_map (List.concat [m_chunk1; m_chunk0]).'
    fixture = chunk.format(0, 1) + chunk.format(1, 2) + join
    entries, order = ordered_entries(fixture, 'm', 'Z * bv 8', PAIR)
    require(entries == [(16, 2), (16, 1)] and order == ['m_chunk1', 'm_chunk0'], 'order regression')
    require(first_map(entries) == {16: 2}, 'first-winner regression')
    sparse = runs([(1, 0), (2, 0), (4, 7), (4, 8)])
    require([(a, bytes(b)) for a, b in sparse] == [(1, b'\x00\x00'), (4, b'\x07'), (4, b'\x08')], 'sparsity/duplicate regression')
    bad = [fixture.replace('(0x2)%Z', '(0x2 + 1)%Z'),
           fixture.replace('m_chunk1; m_chunk0', 'm_chunk0'),
           fixture.replace('m_chunk1; m_chunk0', 'm_chunk1; m_chunk1'),
           fixture.replace('m_chunk1; m_chunk0', 'unknown; m_chunk0'),
           fixture + chunk.format(0, 3)]
    for text in bad:
        try: ordered_entries(text, 'm', 'Z * bv 8', PAIR)
        except ValueError: pass
        else: raise ValueError('malformed source accepted')
    for text in ['(* unclosed', '*)', '(* (* nested *) *)']:
        try: comments_removed(text)
        except ValueError: pass
        else: raise ValueError('malformed comment accepted')
    try: runs([(0, 256)])
    except ValueError: pass
    else: raise ValueError('out-of-range byte accepted')
    print('Parser regression checks passed: join order, first winner, sparse runs, malformed entries/chunks/comments/bytes.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--self-test', action='store_true')
    args = parser.parse_args()
    if args.self_test:
        self_test()
    lock = json.loads((ROOT / 'upstream.lock.json').read_text())
    require(lock['repositories']['xv6iris']['revision'] == PIN, 'lock changed: review and update importer explicitly')
    actual = subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip()
    require(actual == PIN, 'source checkout not paper pin')
    texts, provenance = {}, {}
    for name in FILES:
        data = (args.source / name).read_bytes()
        committed = subprocess.check_output(['git', '-C', str(args.source), 'show', PIN + ':' + name])
        require(data == committed, 'working source differs from pinned git blob: ' + name)
        texts[name] = data.decode('utf-8')
        provenance[name] = {'sha256': hashlib.sha256(data).hexdigest(),
                            'git_blob': subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', PIN + ':' + name], text=True).strip()}
    code, code_order = ordered_entries(texts[FILES[0]], 'kernel_bytes', 'Z * bv 8', PAIR)
    data, data_order = ordered_entries(texts[FILES[1]], 'kernel_data', 'Z * bv 8', PAIR)
    instrs, instr_order = ordered_entries(texts[FILES[0]], 'kernel_instrs', 'Z * kinstr', INSN)
    require((len(code), len(data), len(instrs)) == (23748, 17884, 8607), 'source counts changed')
    require([x[0] for x in instrs] == list(range(8607)), 'instruction index order changed')
    require(all(w in (16, 32) and 0 <= enc < 2**w for _, _, w, enc in instrs), 'invalid instruction encoding')
    cm, dm = first_map(code), first_map(data)
    require(len(cm) == len(code) and len(dm) == len(data), 'pinned map unexpectedly duplicates keys')
    require(not cm.keys() & dm.keys(), 'source maps overlap')
    union = cm | dm
    require(set(union) == set(range(0x80000000, 0x8000a2a0)), 'source file-byte domain changed')
    # Independent host-side ELF evidence: never used to construct map bytes.
    sys.path.insert(0, str(ROOT / 'tools'))
    import images
    raw = images.extract(texts[FILES[4]], 'kernel_elf_hex')
    require(len(raw) == 285560 and hashlib.sha256(raw).hexdigest() == images.IMAGES['KernelElf'][3], 'ELF pin mismatch')
    require(bytes(union[a] for a in range(0x80000000, 0x8000a2a0)) == raw[4096:4096 + 41632], 'source map/ELF host check failed')
    for label, entries in [('code', code), ('data', data)]:
        rs = runs(entries)
        body = 'import Xv6.Kernel.Defs\n\n' + header(FILES[0 if label == 'code' else 1] + ' SHA256 ' + provenance[FILES[0 if label == 'code' else 1]]['sha256'])
        body += '\nnamespace Xv6.Generated.KernelMaps\n\n'
        for i, (base, bs) in enumerate(rs):
            body += f'def {label}Run{i} : Kernel.ByteRun := ⟨0x{base:x}, {len(bs)}, 0x{int.from_bytes(bs, "little"):x}⟩\n\n'
        body += f'def {label}Runs : List Kernel.ByteRun := [' + ', '.join(f'{label}Run{i}' for i in range(len(rs))) + ']\n\nend Xv6.Generated.KernelMaps\n'
        emit(ROOT / ('Xv6/Generated/KernelMaps' + label.title() + '.lean'), body, args.check)
    body = ('import Xv6.Kernel.ImageProofs\nimport Xv6.Generated.KernelMapsCode\nimport Xv6.Generated.KernelMapsData\n\n' +
            header('Kernel-checked packed-slice certificates; payloads come from source maps, not ELF.') +
            '\nset_option exponentiation.threshold 40000\nset_option maxRecDepth 4096\nset_option maxHeartbeats 2000000\n\nnamespace Xv6.Generated.KernelMaps\n\n')
    for label, entries in [('code', code), ('data', data)]:
        for i, (base, bs) in enumerate(runs(entries)):
            name = f'{label}Run{i}'
            page, offset = divmod(4096 + base - 0x80000000, 4096)
            word = f'(Images.kernel.pages[{page}]?.getD 0)'
            body += f'theorem {name}_slice : {name}.payload = ({word} >>> (8 * {offset})) % 2 ^ (8 * {name}.length) := by decide\n\n'
            body += f'theorem {name}_agrees (a : Int) (b : UInt8) (h : {name}.lookup a = some b) :\n    Elf.fileImage Images.kernel a = some b := by\n'
            body += f'  exact Kernel.ByteRun.agrees_fileImage {name} {page} {offset} {word}\n    (by decide) (by decide) (by decide) (by decide) (by decide) {name}_slice a b h\n\n'
    body += 'end Xv6.Generated.KernelMaps\n'
    emit(ROOT / 'Xv6/Generated/KernelMapsCertificates.lean', body, args.check)
    clean = comments_removed(texts[FILES[1]])
    constants = dict(re.findall(r'Definition (kernelMemBase|kernelMemEnd|kernelEntry|kernelRodataEnd|kernel_data_lo|kernel_data_hi) : Z := (0x[0-9a-f]+)%Z\.', clean))
    require(len(constants) == 6, 'missing geometry constants')
    segbody = re.findall(r'Definition kernel_segments : list \(Z \* Z \* Z \* Z\) := \[(.*?)\]\.', clean, re.S)
    require(len(segbody) == 1, 'missing segments')
    segment_rx = re.compile(r'\(\((0x[0-9a-f]+)\)%Z, \((0x[0-9a-f]+)\)%Z, \((0x[0-9a-f]+)\)%Z, \(([0-9]+)\)%Z\)')
    segments = []
    for part in segbody[0].split(';'):
        m = segment_rx.fullmatch(part.strip()); require(m is not None, 'unparsed segment')
        segments.append(tuple(int(x, 0) if x.startswith('0x') else int(x) for x in m.groups()))
    sections = re.findall(r'^\s+(\.[\w.]+)\s+(0x[0-9a-f]+) \.\. (0x[0-9a-f]+)  ([r-][w-][x-])(  \(no file contents\))?$', texts[FILES[1]], re.M)
    require(len(sections) == 7, 'allocated section comment changed')
    syms = re.findall(r'Definition ([\w]+) : Z := (0x[0-9a-f]+)%Z\.', comments_removed(texts[FILES[2]]))
    require(len(syms) == 222 and len(set(n for n, _ in syms)) == 222, 'symbol table changed')
    renames = {dest: orig for orig, dest in re.findall(r"\(\*\s+'([^']+)' -> (\w+) \*\)", texts[FILES[2]])}
    body = 'import Xv6.Kernel.Defs\n\n' + header('Metadata from KernelData.v and KernelSyms.v; source hashes in KernelMapsProvenance.lean.')
    body += '\nnamespace Xv6.Generated.KernelMaps\n\n'
    for name, value in constants.items(): body += f'def {name} : Int := {value}\n'
    body += '\ndef segments : List Kernel.Segment := [\n' + ',\n'.join('  ⟨' + ', '.join(map(str, s)) + '⟩' for s in segments) + '\n]\n\n'
    body += 'def sections : List Kernel.Section := [\n' + ',\n'.join(f'  ⟨{json.dumps(n)}, {lo}, {hi}, {(2 if f[0] == "r" else 0) + (1 if f[1] == "w" else 0) + (4 if f[2] == "x" else 0)}, {str(not bool(nobits)).lower()}⟩' for n, lo, hi, f, nobits in sections) + '\n]\n\n'
    body += 'namespace Symbols\n' + ''.join(f'def «{name}» : Int := {value}\n' for name, value in syms) + 'end Symbols\n\n'
    body += 'def symbols : List Kernel.Symbol := [\n' + ',\n'.join(f'  ⟨{json.dumps(name)}, {json.dumps(renames.get(name, name))}, {value}⟩' for name, value in syms) + '\n]\n\nend Xv6.Generated.KernelMaps\n'
    emit(ROOT / 'Xv6/Generated/KernelMapsMetadata.lean', body, args.check)
    body = 'import Xv6.Kernel.Defs\n\n' + header('Instruction records from KernelInstrs.v, preserving index keys and join order.') + '\nnamespace Xv6.Generated.KernelMaps\n\n'
    for i in range(0, len(instrs), 256):
        body += f'def instructionChunk{i // 256} : List (Int × Kernel.Instruction) := [\n'
        body += ',\n'.join(f'  ({idx}, ⟨0x{addr:x}, {width}, 0x{enc:x}⟩)' for idx, addr, width, enc in instrs[i:i+256]) + '\n]\n\n'
    body += 'def instructionEntries : List (Int × Kernel.Instruction) := [' + ', '.join(f'instructionChunk{i}' for i in range((len(instrs) + 255) // 256)) + '].flatten\n\ndef instruction := Kernel.listMap instructionEntries\n\nend Xv6.Generated.KernelMaps\n'
    emit(ROOT / 'Xv6/Generated/KernelMapsInstructions.lean', body, args.check)
    manifest = {'revision': PIN, 'files': provenance, 'ordered_chunks': {'code': code_order, 'data': data_order, 'instructions': instr_order}, 'counts': {'code': len(code), 'data': len(data), 'instructions': len(instrs), 'symbols': len(syms)}, 'host_elf_comparison': '41632 bytes equal at ELF offset4096; not a Lean proof', 'representation': 'consecutive ordered runs, split at4096 address boundaries; first entry wins; absent addresses none'}
    body = header('Machine-readable provenance below; importer does not prove cross-language parsing.') + '\nnamespace Xv6.Generated.KernelMaps\n\ndef provenanceJSON : String := ' + json.dumps(json.dumps(manifest, sort_keys=True), ensure_ascii=False) + '\n\nend Xv6.Generated.KernelMaps\n'
    emit(ROOT / 'Xv6/Generated/KernelMapsProvenance.lean', body, args.check)
    print('Validated/imported 23748 code bytes, 17884 data bytes, 8607 instructions, 222 symbols; ordered maps match 41632 ELF bytes (host check).')


if __name__ == '__main__':
    try: main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(str(error)) from error
