#!/usr/bin/env python3
"""Emit untrusted row witnesses for kernel-checked ELF symbol certificates.

Authorship note: this was researched and written by an AI coding agent
(OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
posted from this account.
"""
import argparse
import hashlib
import re
import struct
import subprocess
from pathlib import Path

import images
from kernel_maps import PIN, comments_removed

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    revision = subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != PIN:
        raise ValueError('source revision differs from paper pin')
    texts = {}
    for name in ['KernelElfRaw.v', 'KernelSyms.v']:
        rel = 'kernel-rocq/' + name
        data = (args.source / rel).read_bytes()
        committed = subprocess.check_output(['git', '-C', str(args.source), 'show', PIN + ':' + rel])
        if data != committed:
            raise ValueError('modified source: ' + rel)
        texts[name] = data.decode()
    raw = images.extract(texts['KernelElfRaw.v'], 'kernel_elf_hex')
    if len(raw) != 285560 or hashlib.sha256(raw).hexdigest() != images.IMAGES['KernelElf'][3]:
        raise ValueError('kernel image pin mismatch')
    section_offset = struct.unpack_from('<Q', raw, 40)[0]
    section_size, section_count = struct.unpack_from('<HH', raw, 58)
    if section_size != 64:
        raise ValueError('not ELF64 section layout')
    sections = [struct.unpack_from('<IIQQQQIIQQ', raw, section_offset + i * 64)
                for i in range(section_count)]
    tables = [(i, s) for i, s in enumerate(sections) if s[1] == 2]
    if len(tables) != 1:
        raise ValueError('expected one symbol table')
    table_index, table = tables[0]
    if table[9] != 24 or table[5] % 24 or table[2] & 0x800:
        raise ValueError('unsupported symbol table layout')
    strings = sections[table[6]]
    if strings[1] != 3 or strings[2] & 0x800:
        raise ValueError('unsupported string table layout')
    string_bytes = raw[strings[4]:strings[4] + strings[5]]
    found = {}
    for row in range(table[5] // 24):
        name, info, other, index, value, size = struct.unpack_from('<IBBHQQ', raw, table[4] + row * 24)
        if name >= len(string_bytes):
            raise ValueError('name outside string table')
        end = string_bytes.index(0, name)
        key = (string_bytes[name:end].decode('utf-8'), value)
        if index != 0:
            found.setdefault(key, []).append(row)
    source = texts['KernelSyms.v']
    aliases = {dest: orig for orig, dest in re.findall(r"\(\*\s+'([^']+)' -> (\w+) \*\)", source)}
    symbols = re.findall(r'Definition ([\w]+) : Z := (0x[0-9a-f]+)%Z\.', comments_removed(source))
    if len(symbols) != 222:
        raise ValueError('symbol count changed')
    rows = []
    for name, address in symbols:
        matches = found.get((aliases.get(name, name), int(address, 16)), [])
        if len(matches) != 1:
            raise ValueError('missing or ambiguous witness: ' + name)
        rows.append(matches[0])
    out = '''-- Generated by tools/symbol_certificates.py. Do not edit.
-- Witnesses are untrusted until the ordinary Lean kernel checks the certificates.
-- Source: mit-pdos/xv6iris@''' + PIN + '''
-- Kernel software: see LICENSES/xv6-riscv.txt.
-- Authorship note: this was researched and written by an AI coding agent
-- (OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
-- posted from this account.
import Xv6.Kernel.SymbolProofs
import Xv6.Images

namespace Xv6.Generated.KernelSymbolCertificates
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

def tableIndex : Nat := ''' + str(table_index) + '''
def rows : Array Nat := #[''' + ', '.join(map(str, rows)) + ''']

def checkRow (i : Nat) : Option Bool := do
  let expected ← Kernel.symbols[i]?
  let row ← rows[i]?
  pure (Kernel.Symbols.check Images.kernel tableIndex row expected)

theorem all_rows : ∀ i : Fin 222, checkRow i.val = some true := by decide

end Xv6.Generated.KernelSymbolCertificates
'''
    target = ROOT / 'Xv6/Generated/KernelSymbolCertificates.lean'
    if args.check:
        if not target.exists() or target.read_text() != out:
            raise ValueError('generated symbol certificate changed')
    else:
        target.write_text(out)
    print('Verified 222 unique imported symbol witnesses against pinned ELF; Lean checks remain required')


if __name__ == '__main__':
    main()
