#!/usr/bin/env python3
"""Import independent user ELF blobs and emit kernel-checked disk-copy certificates.

Authorship note: this was researched and written by an AI coding agent
(OpenAI Codex), working on Jason Gross's behalf; Jason reviews what is
posted from this account.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import images
import inode_certificates as inode

ROOT = Path(__file__).resolve().parents[1]
PROGRAMS = {
    'Echo': (4, 35592, '31831c6c6681c276a121cca1fda3d85535f5f6d7dfbc3ac1790f76a4b0fa7db3'),
    'Init': (7, 35976, 'b2c05b19834e4f72a3f45470e469ac709118bdff7e0adb15d07b0ac94c635aac'),
    'Sh': (13, 58312, '02b582177e64fc262a37350980a0801ece72dc4d9bcfa77c7692888e8dbb025e'),
    'Sync': (22, 34944, '444ac218c1aa3c8842a44499b224e010685d9bb9dde9f7f059943a6fbbc2b0b7'),
}
NOTE = ('-- Authorship note: this was researched and written by an AI coding agent\n'
        '-- (OpenAI Codex), working on Jason Gross\'s behalf; Jason reviews what is\n'
        '-- posted from this account.\n')
OPTIONS = ('set_option maxRecDepth 20000\nset_option maxHeartbeats 8000000\n'
           'set_option exponentiation.threshold 65536\n\n')


def original_blob(source, relative):
    original = subprocess.check_output(['git', 'show', inode.PIN + ':' + relative], cwd=source)
    actual = (source / relative).read_bytes()
    inode.validate_source(inode.PIN, actual, original)
    return actual


def header(relative, source_bytes, raw):
    return ('-- Generated by tools/user_files.py; do not edit.\n'
            '-- xv6 software: see LICENSES/xv6-riscv.txt for copyright and permission.\n'
            f'-- Source: mit-pdos/xv6iris@{inode.PIN}/{relative}\n'
            f'-- Source SHA256: {hashlib.sha256(source_bytes).hexdigest()}\n'
            f'-- Bytes: {len(raw)}; SHA256: {hashlib.sha256(raw).hexdigest()}\n' + NOTE)


def render(name, raw, source_bytes, disk):
    index, size, digest = PROGRAMS[name]
    low = name.lower()
    relative = f'user-rocq/{name}ElfRaw.v'
    hdr = header(relative, source_bytes, raw)
    record = inode.read_inode(disk, index, inode.EXPECTED_SB[6])
    entries = inode.indirect(disk, record)
    inode.require(record[0] == 2 and record[4] == size, 'file inode type/size mismatch')
    inode.require(inode.check_w3(record, entries, inode.EXPECTED_SB), 'file W3 input mismatch')
    pages = [raw[i:i + 4096] for i in range(0, len(raw), 4096)]
    output = {}
    data = [hdr, 'import Xv6.Image.PackedProofs\n\nnamespace Xv6.Generated.User\n\n']
    for i, page in enumerate(pages):
        expr = images.balanced(page, lambda b: f'"{b:02x}"', lambda a, b: f'({a} ++ {b})')
        data.append(f'def {low}HexPage{i:02d} : String :=\n  {expr}\n\n')
    data.append(f'def {low}HexChunks : List String := [' + ', '.join(f'{low}HexPage{i:02d}' for i in range(len(pages))) + ']\n\n')
    data.append(f'def {low}Packed : Xv6.Image.Packed := ⟨{size}, [\n' + ',\n'.join('  ' + hex(int.from_bytes(page, 'little')) for page in pages) + ']⟩\n\n')
    data.append(f'theorem {low}Covered : {low}Packed.Covered := by unfold Xv6.Image.Packed.Covered; decide\n\nend Xv6.Generated.User\n')
    output[name + 'Data.lean'] = ''.join(data)
    for i, page in enumerate(pages):
        proof = images.balanced(page, lambda b: f'Xv6.Generated.Encoding.byte{b:02x}', lambda a, b: f'(Xv6.Image.hexBlockString_append {a} {b})')
        output[f'{name}Encoding{i:02d}.lean'] = (hdr + 'import Xv6.Generated.EncodingCertificateLeaves\n' +
            f'import Xv6.Generated.User.{name}Data\n\n' + OPTIONS + 'namespace Xv6.Generated.User\n\n' +
            f'theorem {low}Page{i:02d}_encoding : Xv6.Image.HexBlockString {low}HexPage{i:02d} {len(page)} {hex(int.from_bytes(page, "little"))} :=\n  {proof}\n\nend Xv6.Generated.User\n')
    term = f'(.last {low}Page{len(pages)-1:02d}_encoding (by decide))'
    for i in reversed(range(len(pages)-1)):
        term = f'(.full {low}Page{i:02d}_encoding {term})'
    encoding = [hdr] + [f'import Xv6.Generated.User.{name}Encoding{i:02d}\n' for i in range(len(pages))]
    encoding += ['\n' + OPTIONS, 'namespace Xv6.Generated.User\nopen Xv6.Image\n\n',
        f'theorem {low}Encoding : HexPages {low}HexChunks {low}Packed.pages {low}Packed.byteLength :=\n  {term}\n\n',
        f'theorem {low}_decode_eq : decodeChunks {low}HexChunks = some (ByteArray.mk {low}Packed.toBytes.toArray) :=\n  {low}Packed.decode_eq_of_hexPages {low}Encoding\n\n',
        'end Xv6.Generated.User\n']
    output[name + 'Encoding.lean'] = ''.join(encoding)
    blocks = (size + 1023) // 1024
    reader = [hdr, 'import Xv6.Fs.UserFilesProofs\n', f'import Xv6.Generated.User.{name}Data\n',
              f'import Xv6.Generated.InodeW3Leaf{index:02d}\n\n', OPTIONS,
              'namespace Xv6.Generated.User\nopen Xv6.Fs Xv6.Fs.Image Xv6.Generated.InodeW3\n\n']
    for k in range(blocks):
        block = record[5 + k] if k < 12 else entries[k - 12]
        count = min(1024, size - k * 1024)
        offset = block * 1024
        fileoff = k * 1024
        piece = raw[fileoff:fileoff + count]
        inode.require(disk[offset:offset + count] == piece, f'{name}: source ELF/disk disagreement at file offset{fileoff}')
        dp, do = divmod(offset, 4096)
        fp, fo = divmod(fileoff, 4096)
        payload = int.from_bytes(piece, 'little')
        reader += [f'theorem {low}Copy{k:03d} : CopySlice Xv6.Images.disk {low}Packed {offset} {fileoff} {count} :=\n',
            f'  copySlice_of_pages Xv6.Images.disk {low}Packed {dp} {fp}\n',
            f'    ((Xv6.Images.disk.pages[{dp}]?).getD 0) (({low}Packed.pages[{fp}]?).getD 0)\n',
            f'    {do} {fo} {count} {hex(payload)}\n',
            '    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)\n\n',
            f'theorem {low}Block{k:03d} : FileBlockMatch Xv6.Images.disk {low}Packed record{index:02d} {k} := by\n',
            f'  apply fileBlockMatch_of_copy _ _ _ _ {block} {count} {low}Covered\n',
            f'  · change blockAddress blockView record{index:02d} {k} = {block}\n',
            f'    simp only [blockAddress, Nat.reduceLT, ↓reduceIte' + (f', entries{index:02d}_eq' if k >= 12 else '') + ']\n',
            '    decide\n  · decide\n  · decide\n', f'  · exact {low}Copy{k:03d}\n\n']
    term = f'(.nil {blocks})'
    for k in reversed(range(blocks)):
        term = f'(.cons {low}Block{k:03d} {term})'
    reader += [f'theorem {low}BlockCertificates : FileBlockCertificates Xv6.Images.disk {low}Packed record{index:02d} 0 {blocks} :=\n  {term}\n\n',
        f'theorem {low}FileBytes : fileBytes (dataOf blockView record{index:02d}) record{index:02d}.size.toNat = packedFileBytes {low}Packed :=\n',
        f'  fileBytes_of_certificates Xv6.Images.disk {low}Packed record{index:02d} {blocks} (by decide) (by decide) {low}BlockCertificates\n\n',
        'end Xv6.Generated.User\n']
    output[name + 'Disk.lean'] = ''.join(reader)
    return output


def validate_user_bytes(name, raw):
    _, size, digest = PROGRAMS[name]
    inode.require(len(raw) == size and hashlib.sha256(raw).hexdigest() == digest,
                  'user ELF byte hash/size mismatch')


def user_self_test(name, raw, source_bytes, disk):
    def rejected(action, expected):
        try:
            action()
        except ValueError as error:
            inode.require(expected in str(error), 'negative test rejected for the wrong reason')
        else:
            raise ValueError('negative test unexpectedly accepted')
    rejected(lambda: validate_user_bytes(name, raw[:-1]), 'hash/size')
    damaged = bytearray(raw)
    damaged[-1] ^= 1
    rejected(lambda: validate_user_bytes(name, damaged), 'hash/size')
    index, size, _ = PROGRAMS[name]
    record = inode.read_inode(disk, index, inode.EXPECTED_SB[6])
    entries = inode.indirect(disk, record)
    k = (size - 1) // 1024
    block = record[5 + k] if k < 12 else entries[k - 12]
    final_address = block * 1024 + (size - 1) % 1024
    corrupted = bytearray(disk)
    corrupted[final_address] ^= 1
    rejected(lambda: render(name, raw, source_bytes, corrupted), 'source ELF/disk disagreement')
    # The exact file length excludes the remaining allocated-block padding.
    padding = bytearray(disk)
    padding[final_address + 1] ^= 1
    inode.require(render(name, raw, source_bytes, padding) == render(name, raw, source_bytes, disk),
                  'file certificate accidentally constrained bytes after EOF')
    print('User-file negative tests passed: truncation, final ELF byte, final disk byte; post-EOF padding excluded.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--self-test', action='store_true')
    args = parser.parse_args()
    lock = json.loads((ROOT / 'upstream.lock.json').read_text())
    revision = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=args.source, text=True).strip()
    inode.require(revision == lock['repositories']['xv6iris']['revision'] == inode.PIN, 'source pin mismatch')
    if args.self_test:
        inode.self_test()
    disk = images.extract(original_blob(args.source, inode.RAW).decode(), 'fsimg_hex')
    inode.require(len(disk) == 2048000 and hashlib.sha256(disk).hexdigest() == inode.DIGEST, 'disk byte hash/size mismatch')
    output = {}
    for name, (_, size, digest) in PROGRAMS.items():
        source_bytes = original_blob(args.source, f'user-rocq/{name}ElfRaw.v')
        raw = images.extract(source_bytes.decode(), name.lower() + '_elf_hex')
        validate_user_bytes(name, raw)
        if args.self_test and name == 'Echo':
            user_self_test(name, raw, source_bytes, disk)
        output.update(render(name, raw, source_bytes, disk))
    for name, text in output.items():
        inode.emit(ROOT / 'Xv6/Generated/User' / name, text, args.check)
    print(f'Reproduced four independent ELF inputs and {len(output)} checked-certificate source modules.')


if __name__ == '__main__':
    main()
